### PR TITLE
Apply a style to a defined cell range without passing a list of values.

### PR DESCRIPTION
**Pull request by nedmarinov**
Hello
Didn't found a method to apply a cell style to a range without passing values for all the cells.
I needed to style a range of cells without the need to pass values ​​to them.
Right now, from what I've seen, styles can only be applied to new cells or ranges with predefined series of values.
If, for example, you want to apply styles to cells that for whatever reason remain empty (without value, so they actually are not created by AddCell) in a range, the final excel will have some cells with styles and others without them.

### CODE REVIEW

**Comment by rabanti-github** [comment]
Hello
Thank you for the contribution.
I will have a look at it as quick as possible.

**Comment by rabanti-github** [comment]
Hello
Sorry for the delay. Unfortunately, I cannot merge this PR in its current state. There are several issues with it. Please let me explain and propose a solution.
### Analysis
1.	It is probably not intuitive for the API user, if only one single overload method is defined with the changes you propose. It should apply to all kinds of similar methods like:
a.	AddCell with Address as string AND Address object
b.	AddNextCell (maybe questionable)
c.	AddCellRange with address as string, start and end Address objects and Range object
To serve only one single use case should not be the goal of the library 
2.	I think what you want to achieve is to define styles and not new cells. Technically there are new cells created in Excel, if you define a style on it, but probably not as you implemented. “Empty” cells are by default numeric, but the implementation adds string cells. However, it is a mixed problem, regarding the PR implementation and the way, how the library handles empty cells. Internally empty is added as empty string and not an “empty” number (we cannot add a null int32 primitive datatype). This was wrong implemented by me, under the assumption that only cells with values are added.
3.	You don’t need to define an own, almost identical method AddCellrangeInternal(). The existing one could be reused by method chaining (define a list of addresses and pass it with “empty” [see point 2].
4.	As I assume that you want to set styles to yet undefined cells (e.g., as template), AddCellRange() is probably not the right terminology . Would be better something like SetStyle() on the worksheet with several overloads

### Proposal
So, here is my proposal:

-	Since my definition of the empty cell is wrong anyway, I have to change the internal functions, deep down in the low-level classes of the library
-	Instead of an extension of the AddCellRange() method, a new method, called SetStyle() is introduced in the Worksheet class. I can define this as well.
-	This new method has four overloaded representations
o	SetStyle(String, Style) &rarr; Can be a single cell or a cell range, also over multiple rows and columns
o	SetStyle(Address, Style) &rarr; For a single cell
o	SetStyle(Address, Address, Style) &rarr;  For a range with two components
o	SetStyle(Range, Style) &rarr; Same as above, but combined
-	The advantage of such a method would be that already existing cells could be redefined (its styles, respectively)

So, I would reject this PR and provide the described function above, hopefully the next few days, instead. I have anyway two pending PRs that must be merged as well.
Please let me know, if my assumptions of your intentions were wrong. And thank you, for pointing out the missing functionality.

**Comment by rabanti-github** [comment]
You find a completely untested preview of this proposal on the [Dev-Branch](https://github.com/rabanti-github/NanoXLSX/tree/dev)

**Comment by rabanti-github** [comment]
@nedmarinov The proposal is no on master and released as v1.6.
Please let me know with a new issue if something is missing.
I will close this PR for now. 
Thank you.

**Comment by nedmarinov** [comment]
Hello
Thanks you for your analysis and proposal, it's very helpful.
Your assumption is correct, I wanted to lay out undefined cells as my Excel doesn't necessarily have all cells filled.
I tested with the v1.6 and didn't found any issue.

**Pull request closed without merging**
