### PR TITLE
public void AddCellRange(IEnumerable<object> values,

### PR DESCRIPTION
**Pull request by Shobb**
Change:
void AddCellRange(IEnumerable<object> values,..
To =>
AddCellRange(IReadOnlyList<object> values,...

### CODE REVIEW

**Comment by rabanti-github** [comment]
Please give a reason why this (and particularly only this section) should be changed form the generic IEnumerable to something more specific. Thank you in advance for the reasoning and a possible discussion about a possible disadvantage of IEnumerable.

**Comment by Shobb** [comment]
I'll make new pull request.

**Comment by Shobb** [comment]
Hello Raphael, I closed this pull request, - and opened new, because I made more changes.In comments, I try to explain the reasons. I have already made this change in the program, which uses NanoXMLS – it was necessary. Best regards,Thank you for good library. 27.12.2020, 06:20, "Raphael Stoeckli" <notifications@github.com>: Please give a reason why this (and particularly only this section) should be changed form the generic IEnumerable to something more specific. Thank you in advance for the reasoning and a possible discussion about a possible disadvantage of IEnumerable.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rabanti-github** [comment]
Hi.
I recently merged the PR to the dev branch, since I have to do some additional things before I can release. See the comment on the PR. Thank you. I will inform you as soon the release is done.

**Pull request closed without merging**
